baseurl = "https://clayyount.com"
languageCode = "en-us"
title = "Homepage"
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS", "JSON"]
[permalinks]
raecomic = "/:section/:year/:month/:day/:title/"
hamlets-danish-comic = "/:section/:year/:month/:day/:title/"
ghostcat-comics-archive = "/:section/:year/:month/:day/:title/"
blog = "/:section/:year/:month/:day/:title/"
